# Generated by Django 3.1.5 on 2021-01-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
    ]
