# Generated by Django 3.1.5 on 2021-01-29 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corn', '0002_remove_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
