# Generated by Django 3.1.5 on 2021-02-02 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corn', '0004_auto_20210202_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpokemon',
            name='pokemon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corn.pokemon'),
        ),
    ]
