# Generated by Django 3.1.5 on 2021-02-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corn', '0005_auto_20210202_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpokemon',
            old_name='pokemon_id',
            new_name='pokemon',
        ),
        migrations.RenameField(
            model_name='userpokemon',
            old_name='user_id',
            new_name='user',
        ),
    ]
